module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      animation: {
        shimmer: "shimmer 3s ease-out infinite alternate",
        opacity: "opacity 0.25s ease-in-out",
        appearFromRight: "appearFromRight 300ms ease-in-out",
        wiggle: "wiggle 1.5s ease-in-out infinite",
        popup: "popup 0.25s ease-in-out",
      },
      fontFamily: {
        display: ["Satoshi", "sans-serif"],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      {
        fancyflare: {
          "base-100": "#f5f5f0",
          "base-200": "#e8e8e0",
          "base-300": "#d4d4c8",
          "base-content": "#3d4a2e",
          primary: "#4db8b0",
          "primary-content": "#f0faf9",
          secondary: "#d48b2a",
          "secondary-content": "#fdf8ee",
          accent: "#3dba6e",
          "accent-content": "#f0fdf4",
          neutral: "#2d3a1e",
          "neutral-content": "#f5f5f0",
          info: "#3b82f6",
          "info-content": "#eff6ff",
          success: "#3dba6e",
          "success-content": "#f0fdf4",
          warning: "#d48b2a",
          "warning-content": "#fdf8ee",
          error: "#e03d2a",
          "error-content": "#fef2f0",
        },

        doubleprime: {
          "base-100": "#3d1a1c",
          "base-200": "#5a2528",
          "base-300": "#6b2d30",
          "base-content": "#f0e0e5",
          primary: "#3dba6e",
          "primary-content": "#f0fdf4",
          secondary: "#3dba6e",
          "secondary-content": "#f0fdf4",
          accent: "#000000",
          "accent-content": "#ffffff",
          neutral: "#e0404a",
          "neutral-content": "#faf0f5",
          info: "#60b8e0",
          "info-content": "#1a2a40",
          success: "#7dd87a",
          "success-content": "#1a3d1c",
          warning: "#e8d44d",
          "warning-content": "#2a2010",
          error: "#d97040",
          "error-content": "#2a1008",
        },
      },
    ],
  },
};
